### ISSUE TITLE
How to load the backup.dat file

### ISSUE THREAD

**Issue by Oliver7580** [spectrecoin/spectre#14] opened 2017-10-02 19:12 UTC
Hello
How do i use the backup.dat for wallet restoring?

**Comment by jbg** [comment] 2017-10-03 15:21
If `backup.dat` is simply a backup copy of `wallet.dat` from a previous SpectreCoin wallet, just make sure the Spectre wallet is not running, and then copy it into your data directory (on Linux, it's `$HOME/.spectrecoin`, on Windows it's a folder called SpectreCoin inside your Windows profile application data directory). Make sure it is named `wallet.dat`. Then launch the wallet again.

**Comment by Oliver7580** [comment] 2017-10-03 16:43
Thank you for your reply,i am on Windows 10,but i can't find the folder,that you mean.i only found the normal folder where the .exe is in.

**Comment by Oliver7580** [comment] 2017-10-06 12:59
Hello I still have not found the right folder :(

**Comment by bitcoinx2** [comment] 2017-10-08 14:34
Please come to Slack and let me help you there, Oliver. https://slack.spectreproject.io

**Comment by jbg** [comment] 2017-10-08 17:42
Closing because, as @bitcoinx2 points out, this is not a bug but a support request. Please join slack and ask for help :)

**Closed by jbg** 2017-10-08 17:42 UTC
